angular.module('myApp').constant("type",[
	{type:"CSS",value:0},
	{type:"JS",value:1},
	{type:"JAVA",value:2},
	{type:"运维",value:3},
	{type:"DBA",value:4},
	{type:"产品",value:5},
	{type:"IOS",value:6},
	{type:"ANDROID",value:7}
])
.constant("level",[
	{level:"0基础",value:0},
	{level:"修行3个月以内",value:1},
	{level:"修行6个月以内",value:2},
	{level:"修行1年以内",value:3},
	{level:"修行3年以内",value:4},
	{level:"修行3年以上",value:5}
	])
.constant("talent",[
	{talent:"学霸",value:0},
	{talent:"学渣",value:1}
	])